#!/usr/bin/env python3
"""Generate ~/.config/polybar/config.ini with glyphs written from codepoints.

Every glyph is verified against the installed fonts first; a missing one is a
hard error rather than a silently blank bar.
"""
import pathlib
import sys
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from cmap import coverage

G = {
    "firefox": 0xF0239, "android": 0xF0032, "terminal": 0xF018D,
    "folder": 0xF024B, "code": 0xF0A1E, "music": 0xF075A, "chat": 0xF0B79,
    "image": 0xF02E9, "video": 0xF0567, "cog": 0xF0493, "circle": 0xF0765,
    "vol_high": 0xF057E, "vol_med": 0xF0580, "vol_mute": 0xF0581,
    "bright_low": 0xF00DE, "bright_med": 0xF00DF, "bright_high": 0xF00E0,
    "cpu": 0xF0EE0, "memory": 0xF035B,
    "wifi": 0xF05A9, "wifi_off": 0xF05AA,
    "bat_10": 0xF007A, "bat_30": 0xF007C, "bat_50": 0xF007E,
    "bat_70": 0xF0080, "bat_full": 0xF0079, "bat_chg": 0xF0084,
    "clock": 0xF0954, "power": 0xF0425,
}

cov = coverage()
missing = {k: v for k, v in G.items() if v not in cov}
if missing:
    for k, v in missing.items():
        print(f"MISSING U+{v:05X}  {k}", file=sys.stderr)
    sys.exit("aborting: font is missing glyphs listed above")

c = {k: chr(v) for k, v in G.items()}

CONFIG = f""";  Polybar - Catppuccin Mocha
;  Generated by gen_polybar.py. Glyphs are written from verified codepoints;
;  if you hand-edit this file, do not retype the icons - copy them.

[colors]
base      = #1e1e2e
mantle    = #181825
crust     = #11111b
surface0  = #313244
surface1  = #45475a
text      = #cdd6f4
subtext   = #a6adc8
dim       = #7f849c
blue      = #89b4fa
lavender  = #b4befe
sapphire  = #74c7ec
teal      = #94e2d5
green     = #a6e3a1
yellow    = #f9e2af
peach     = #fab387
red       = #f38ba8
mauve     = #cba6f7

[bar/main]
monitor         = ${{env:MONITOR:}}
width           = 100%
height          = 30pt
radius          = 0
dpi             = 96

background      = ${{colors.base}}
foreground      = ${{colors.text}}

line-size       = 2pt
border-size     = 0
padding-left    = 0
padding-right   = 1
module-margin   = 1

font-0 = JetBrainsMono Nerd Font:style=Bold:size=10;3
font-1 = JetBrainsMono Nerd Font:style=Regular:size=10;3
font-2 = Symbols Nerd Font:size=13;4

; Open windows sit immediately right of the workspaces rather than centred,
; so the list grows away from the status modules instead of toward them.
modules-left   = i3 tasklist
modules-center =
modules-right  = pulseaudio backlight cpu memory wlan battery wordclock power

cursor-click  = pointer
enable-ipc    = true

; Bar-level tray. polybar 3.7 calls these deprecated in favour of an
; internal/tray module, but that module stalls the render loop when it cannot
; claim the systray selection, so the older mechanism stays.
tray-position   = right
tray-padding    = 4
tray-maxsize    = 18
tray-background = ${{colors.base}}

[module/i3]
type = internal/i3
pin-workspaces = true
show-urgent = true
strip-wsnumbers = true
index-sort = true
enable-click = true
enable-scroll = false
fuzzy-match = true

ws-icon-0 = 1;{c['firefox']}
ws-icon-1 = 2;{c['android']}
ws-icon-2 = 3;{c['terminal']}
ws-icon-3 = 4;{c['folder']}
ws-icon-4 = 5;{c['code']}
ws-icon-5 = 6;{c['music']}
ws-icon-6 = 7;{c['chat']}
ws-icon-7 = 8;{c['image']}
ws-icon-8 = 9;{c['video']}
ws-icon-9 = 10;{c['cog']}
ws-icon-default = {c['circle']}

format = <label-state><label-mode>

label-mode = %mode%
label-mode-padding = 2
label-mode-foreground = ${{colors.crust}}
label-mode-background = ${{colors.peach}}

; %name% is kept alongside %icon% so a workspace can never render as a blank
; clickable block.
label-focused = %icon% %name%
label-focused-foreground = ${{colors.crust}}
label-focused-background = ${{colors.blue}}
label-focused-padding = 2

label-unfocused = %icon% %name%
label-unfocused-foreground = ${{colors.dim}}
label-unfocused-padding = 2

label-visible = %icon% %name%
label-visible-foreground = ${{colors.text}}
label-visible-background = ${{colors.surface0}}
label-visible-padding = 2

label-urgent = %icon% %name%
label-urgent-foreground = ${{colors.crust}}
label-urgent-background = ${{colors.red}}
label-urgent-padding = 2

; Open windows on the focused workspace. Long-running and event-driven:
; it repaints on i3 events instead of polling, so it costs nothing when idle.
[module/tasklist]
type = custom/script
exec = /home/anzar/.local/bin/i3-tasklist
tail = true
format = <label>
label = %output%

[module/pulseaudio]
type = internal/pulseaudio
interval = 5
format-volume = <ramp-volume> <label-volume>
label-volume = %percentage%%
label-volume-foreground = ${{colors.text}}
format-muted = <label-muted>
label-muted = "{c['vol_mute']} muted"
label-muted-foreground = ${{colors.dim}}
ramp-volume-0 = {c['vol_mute']}
ramp-volume-1 = {c['vol_med']}
ramp-volume-2 = {c['vol_high']}
ramp-volume-foreground = ${{colors.sapphire}}
click-right = pavucontrol

[module/backlight]
type = internal/backlight
card = intel_backlight
use-actual-brightness = true
enable-scroll = true
format = <ramp> <label>
label = %percentage%%
label-foreground = ${{colors.text}}
ramp-0 = {c['bright_low']}
ramp-1 = {c['bright_med']}
ramp-2 = {c['bright_high']}
ramp-foreground = ${{colors.yellow}}

[module/cpu]
type = internal/cpu
interval = 5
format = <label>
format-prefix = "{c['cpu']} "
format-prefix-foreground = ${{colors.mauve}}
label = %percentage:2%%
label-foreground = ${{colors.text}}

[module/memory]
type = internal/memory
interval = 10
format = <label>
format-prefix = "{c['memory']} "
format-prefix-foreground = ${{colors.teal}}
label = %percentage_used%%
label-foreground = ${{colors.text}}

[module/wlan]
type = internal/network
interface = wlp0s20f3
interface-type = wireless
interval = 10
format-connected = <label-connected>
label-connected = "{c['wifi']} %essid:0:12%"
label-connected-foreground = ${{colors.text}}
format-disconnected = <label-disconnected>
label-disconnected = "{c['wifi_off']} off"
label-disconnected-foreground = ${{colors.dim}}
click-left = nm-connection-editor

[module/battery]
type = internal/battery
battery = BAT1
adapter = ACAD
low-at = 15
poll-interval = 10
format-charging = <animation-charging> <label-charging>
label-charging = %percentage%%
label-charging-foreground = ${{colors.green}}
format-discharging = <ramp-capacity> <label-discharging>
label-discharging = %percentage%%
label-discharging-foreground = ${{colors.text}}
format-full = <label-full>
label-full = "{c['bat_full']} %percentage%%"
label-full-foreground = ${{colors.green}}
format-low = <ramp-capacity> <label-low>
label-low = %percentage%%
label-low-foreground = ${{colors.red}}
ramp-capacity-0 = {c['bat_10']}
ramp-capacity-1 = {c['bat_30']}
ramp-capacity-2 = {c['bat_50']}
ramp-capacity-3 = {c['bat_70']}
ramp-capacity-4 = {c['bat_full']}
ramp-capacity-foreground = ${{colors.peach}}
animation-charging-0 = {c['bat_chg']}
animation-charging-foreground = ${{colors.green}}
animation-charging-framerate = 1000

; The clock reads as a person would say it aloud ("Saturday, quarter past
; nine") rather than as a timestamp. See ~/.local/bin/i3-wordclock; set
; SHOW_DAY = False in that script to drop the weekday.
[module/wordclock]
type = custom/script
exec = /home/anzar/.local/bin/i3-wordclock
interval = 30
format = <label>
format-prefix = "{c['clock']} "
format-prefix-foreground = ${{colors.lavender}}
label = %output%
label-foreground = ${{colors.lavender}}

[module/power]
type = custom/text
format = "{c['power']}"
format-foreground = ${{colors.red}}
format-background = ${{colors.surface0}}
format-padding = 2
click-left = /home/anzar/.local/bin/i3-powermenu

[settings]
screenchange-reload = true
pseudo-transparency = false
"""

out = "/home/anzar/.config/polybar/config.ini"
with open(out, "w", encoding="utf-8") as fh:
    fh.write(CONFIG)

# read back and confirm the glyphs survived the round-trip
back = open(out, encoding="utf-8").read()
lost = [f"U+{v:05X} {k}" for k, v in G.items() if chr(v) not in back]
print(f"wrote {out}")
print("glyph round-trip:", "ALL OK" if not lost else f"LOST {lost}")
if lost:
    sys.exit(1)
